from exception.base_exception import BaseGuardException


class ArgumentOutOfRangeException(BaseGuardException):
    pass
